
const WIDGETS: string[] = [
  'clock',
  'weather',
  'news-feed',
  'spacer',
  'calendar',
  'voice',
  'qr',
  'compliments',
  'reminders',
  'speed-cameras',
  'stats',
  'travel-time',
  'weather-forecast',
  'text-clock',
  'hue',
  'quote',
  'notifications',
  'version-viewer',
  'speech',
  'spotify',
  'crypto-list',
  'crypto-graph',
  'rain-radar',
  'todos',
  'trains',
  'flights',
  'nest',
  'video-player',
  'speedtest',
  'profile',
  'stocks',
  'formula1',
  'mercedes',
  'github-stars',
  'text',
  'internet-connection',
  'reddit'
];

export default WIDGETS;