
name: Senses - Test & Build

on: [pull_request, workflow_dispatch]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.20.0'

      - name: Lint, Test & Build GUI
        working-directory: ./src/gui
        run: |
          npm install --force --package-lock-only
          npm ci --quiet --no-progress
          npm run lint
          npm run build

      - name: Lint, Test & Build Server
        working-directory: ./src/server
        run: |
          npm ci --ignore-scripts
          npm run build:js

      - name: Lint, Test & Build Web app
        working-directory: ./src/app
        run: |
          npm ci --quiet --no-progress
          npm run lint
          npm run build
